class Config(object):
	# RFCT - Design flaw, didn't think of it earlier, but only 9 tiles possible with current configuration =/
	GROUND = 0
	WALL = 1
	BRICK = 2
	BOMB_UP = 3
	POWER_UP = 4
	ARMOR = 5
	LIFE_UP = 6
	TIME_UP = 7
	POWER_PLUS = 8
	WALL_PASS = 9
	FPS = 30
	WIDTH = 840
	HEIGHT = 690
	TILE_SIZE = 40
	IMAGE_PATH = "resources/images/"
	AUDIO_PATH = "resources/sounds/"
	HIGHSCORES_PATH = "resources/highscores.txt"
	SINGLE = 'Single'
	MULTI = 'Multi'
	MAX_ENEMY_SPRITES = 9
	LOCALHOST = False
